apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamer-portal-deployment
  labels:
    app: streamer-portal
  namespace: streamer-portal-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: streamer-portal
  template:
    metadata:
      labels:
        app: streamer-portal
    spec:
      containers:
      - name: streamer-portal
        image: gcr.io/final-project-413218/streamer-portal:v1
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "50Mi"
            cpu: "50m"
          limits:
            memory: "50Mi"
            cpu: "50m"
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: streamer-portal-service
  namespace: streamer-portal-namespace
spec:
  type: LoadBalancer
  selector:
    app: streamer-portal
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
